### ISSUE TITLE
Error in run

### ISSUE THREAD

**Issue by karopass** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#10]
Hi!
I have successfully installed all required module and trying to run but getting error like below

```
C:\Users\Administrator\Desktop\WhatsApp>python run.py

DevTools listening on ws://127.0.0.1:12269/devtools/browser/ff894e12-c951-4d03-b530-9773893f65c0
[5188:1608:0513/065345.725:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.
Unable to read VR Path Registry from C:\Users\Administrator\AppData\Local\openvr\openvrpaths.vrpath
[5188:5444:0513/065351.418:ERROR:audio_manager_base.cc(368)] Invalid audio output parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits Per Sample: 0, Frames Per Buffer: 0
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    whatsapp = WhatsApp(10)
  File "C:\Users\Administrator\Desktop\WhatsApp\whatsapp.py", line 43, in __init__
    (By.XPATH, '//*[@id="side"]/div[2]/div/label/input')))
  File "C:\ProgramData\Miniconda2\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

Let me know if anything I am missing in this.
Thanks

**Comment by VISWESWARAN1998** [comment]
You should consider increasing the timeout

**Comment by vaibhavgeek** [comment]
@karopass Were you able to solve the issue by increasing the timout? I am also facing the same error.
