### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nadif15** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#21]
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from whatsapp import WhatsApp
  File "/root/Downloads/Simple-Yet-Hackable-WhatsApp-api-master/whatsapp.py", line 25, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse

**Comment by nadif15** [comment]
sory idk if use python3
