### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by nadif15** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#22]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from whatsapp import WhatsApp
  File "/root/Downloads/Simple-Yet-Hackable-WhatsApp-api-master/whatsapp.py", line 36, in <module>
    class WhatsApp:
  File "/root/Downloads/Simple-Yet-Hackable-WhatsApp-api-master/whatsapp.py", line 41, in WhatsApp
    browser = webdriver.Chrome()  # we are using chrome as our webbrowser
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=72.0.3626.53,platform=Linux 4.19.0-kali3-amd64 x86_64)

**Comment by VISWESWARAN1998** [comment]
Are you sure the chrome is in correct path?
Please make sure that Google chrome has been installed in correct path. 

Create a new test python file and try running this code:

```python
from selenium import webdriver

browser = webdriver.Chrome()
browser.get("https://www.google.com")
```

If the above code runs without any errors, please do contact me. It seems more like a problem in selenium and chrome configuration rather than this API.

Thank you!
Visweswaran N

**Comment by nadif15** [comment]
still error 

>>> browser = webdriver.Chrome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=72.0.3626.53,platform=Linux 4.19.0-kali3-amd64 x86_64)

**Comment by nadif15** [comment]
ok is fixed another problem appear 

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    whatsapp = WhatsApp(10)
  File "/home/testonly/Downloads/Simple-Yet-Hackable-WhatsApp-api-master/whatsapp.py", line 51, in __init__
    (By.CSS_SELECTOR, '.jN-F5')))
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by nadif15** [comment]
oh i got it time limit ok ty

**Comment by nadif15** [comment]
ok is time limit but, is still not work just buff in chrome

**Comment by VISWESWARAN1998** [comment]
Can you paste the code which throws the error here. Thank you!

**Comment by nadif15** [comment]
no code just in web buff non stop

**Comment by nadif15** [comment]
site cant be reach

**Comment by VISWESWARAN1998** [comment]
You should have used my API code right? send the code!

**Comment by nadif15** [comment]
from whatsapp import WhatsApp
whatsapp = WhatsApp(100)
print(whatsapp.send_message("Mori","thx!"))

**Comment by VISWESWARAN1998** [comment]
I think everything works. This is just an automation script. **QR code needs to scanned manually!**

Thank you!
Visweswaran N

**Comment by nadif15** [comment]
all fine until i run your code maybe i got ban :(

**Comment by VISWESWARAN1998** [comment]
You cannot be banned for an automation script which sends one single message.
