### ISSUE TITLE
Error while getting whatsapp status

### ISSUE THREAD

**Issue by SagarMahadik** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#29]
Hi,

First of all thank you for the api!

I am getting below error while looking for "Status" of contact.

Kindly look into this

C:\Users\Sagar\AppData\Local\Programs\Python\Python37\python.exe C:/Users/Sagar/Downloads/Simple-Yet-Hackable-WhatsApp-api-master/Simple-Yet-Hackable-WhatsApp-api-master/group.py
Traceback (most recent call last):
  File "C:\Users\Sagar\Downloads\Simple-Yet-Hackable-WhatsApp-api-master\Simple-Yet-Hackable-WhatsApp-api-master\whatsapp.py", line 185, in get_status
    (By.XPATH, group_xpath)))
  File "C:\Users\Sagar\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Sagar/Downloads/Simple-Yet-Hackable-WhatsApp-api-master/Simple-Yet-Hackable-WhatsApp-api-master/group.py", line 3, in <module>
    print(whatsapp.get_status("Ketan"))
  File "C:\Users\Sagar\Downloads\Simple-Yet-Hackable-WhatsApp-api-master\Simple-Yet-Hackable-WhatsApp-api-master\whatsapp.py", line 188, in get_status
    raise TimeoutError("Your request has been timed out! Try overriding timeout!")
TimeoutError: Your request has been timed out! Try overriding timeout!

Process finished with exit code 1

**Comment by VISWESWARAN1998** [comment]
Can you post your code for me to execute and fix this. Apologies for the late reply
